/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Punk API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package dev.klevente.portabledogdiy.data.network.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property mashTemp
 * @property fermentation
 */
@JsonClass(generateAdapter = true)
data class Method(
    @Json(name = "mash_temp") @field:Json(name = "mash_temp") var mashTemp: List<Mash>,
    @Json(name = "fermentation") @field:Json(name = "fermentation") var fermentation: Fermentation
)
