/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Punk API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package dev.klevente.portabledogdiy.data.network.models

typealias BeersResponse = List<BeerResponse>
