/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Punk API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package dev.klevente.portabledogdiy.data.network.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property malt
 * @property hops
 * @property yeast
 */
@JsonClass(generateAdapter = true)
data class Ingredients(
    @Json(name = "malt") @field:Json(name = "malt") var malt: List<Malt>,
    @Json(name = "hops") @field:Json(name = "hops") var hops: List<Hop>,
    @Json(name = "yeast") @field:Json(name = "yeast") var yeast: String
)
